language: node_js

node_js:
  - "8"
  - "6"
  - "4"

services:
  - docker

cache:
  directories:
    - "node_modules"

before_script:
  - docker run -d -p 127.0.0.1:1883:1883 ansi/mosquitto

script:
  - make quality
  - make test

