// flow-typed signature: e6c09c1a4a7eca2e9d570829c1c967df
// flow-typed version: <<STUB>>/babel-preset-ttn_v^1.2.3/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-ttn'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-ttn' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-preset-ttn/browser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-preset-ttn/browser.js' {
  declare module.exports: $Exports<'babel-preset-ttn/browser'>;
}
declare module 'babel-preset-ttn/index' {
  declare module.exports: $Exports<'babel-preset-ttn'>;
}
declare module 'babel-preset-ttn/index.js' {
  declare module.exports: $Exports<'babel-preset-ttn'>;
}
