// flow-typed signature: 02cf398f1ac56a765d97c2af049edb9f
// flow-typed version: <<STUB>>/grpc-tools_v^1.4.1/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'grpc-tools'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'grpc-tools' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'grpc-tools/bin/protoc_plugin' {
  declare module.exports: any;
}

declare module 'grpc-tools/bin/protoc' {
  declare module.exports: any;
}

// Filename aliases
declare module 'grpc-tools/bin/protoc_plugin.js' {
  declare module.exports: $Exports<'grpc-tools/bin/protoc_plugin'>;
}
declare module 'grpc-tools/bin/protoc.js' {
  declare module.exports: $Exports<'grpc-tools/bin/protoc'>;
}
declare module 'grpc-tools/index' {
  declare module.exports: $Exports<'grpc-tools'>;
}
declare module 'grpc-tools/index.js' {
  declare module.exports: $Exports<'grpc-tools'>;
}
