// flow-typed signature: 922d87c9bbc437c30383e2a378c75ffe
// flow-typed version: <<STUB>>/jest-preset-ttn_v^0.0.3/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-preset-ttn'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-preset-ttn' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-preset-ttn/files.transform' {
  declare module.exports: any;
}

declare module 'jest-preset-ttn/styles.transform' {
  declare module.exports: any;
}

declare module 'jest-preset-ttn/transform' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-preset-ttn/files.transform.js' {
  declare module.exports: $Exports<'jest-preset-ttn/files.transform'>;
}
declare module 'jest-preset-ttn/styles.transform.js' {
  declare module.exports: $Exports<'jest-preset-ttn/styles.transform'>;
}
declare module 'jest-preset-ttn/transform.js' {
  declare module.exports: $Exports<'jest-preset-ttn/transform'>;
}
